# This file is unfinished. It is meant to be used in the development of an in-tool game configurator
# (see TODO file)

extends Node

# CONSTANTES (podem ser alteradas, resultando num jogo diferente)
var ANO_INICIAL = 2014
var FINAL_YEAR = 2050

var POTENCIA_MAXIMA_SOLAR = 9.300 #GW
var POTENCIA_MAXIMA_VENTO = 7.500
var POTENCIA_MAXIMA_BIOMASSA= 47.230

var CUSTO_POR_GIGAWATT_INSTALADO = 2100 #???? #euro/GW #necessário dividir por tipo de energia

var PERCENTAGEM_A_RETIRAR_DO_PIB = 0.16 #cenário pessimista

var POPULACAO =  6800505 #2014
var ALFA = 1270 #cenário pessimista
var HORAS_POR_ANO = 8760 #24 * 365

var PERCENTAGEM_INPUT_SETAS = 0.005 #0.5% (A CONFIRMAR)

var EFICIENCIA_TRANSPORTES = 0.0128 #???? #valores a corrigir #na passagem de exergia final para útil
var EFICIENCIA_INDUSTRIA = 0.2484 #????
var EFICIENCIA_RESIDENCIAL = 0.1972 #????
var EFICIENCIA_SERVICOS = 0.3046 #????

var FATOR_DE_EMISSAO_CARVAO = 94.6 #kg CO2 / TJ
var FATOR_DE_EMISSAO_PETROLEO = 74.3 
var FATOR_DE_EMISSAO_GAS_NATURAL = 56.1
var FATOR_DE_EMISSAO_COMB_RENOVAVEIS = 0.00

var FATOR_DE_PRODUCAO_SOLAR = 0.1960
var FATOR_DE_PRODUCAO_VENTO = 0.2690
var FATOR_DE_PRODUCAO_BIOMASSA = 0.4920
var FATOR_DE_PRODUCAO_HIDRO = 0.1180

var POTENCIA_ANUAL_HIDRO = 5.57 #GW

var INEFICIENCIA_PRIMARIO_PARA_FINAL = 1.1

var MAXIMO_PRODUZIDO_POR_GAS_NATURAL = 13550 #GWh

var EFICIENCIA_DE_PRODUCAO_DE_ELETRICIDADE_COM_GAS_NATURAL = 0.55
var EFICIENCIA_DE_PRODUCAO_DE_ELETRICIDADE_COM_CARVAO = 0.40

# VALORES DO ANO ZERO (e.g. 2014)
var POTENCIA_DO_ANO_ZERO_SOLAR = 0.493 #GW
var POTENCIA_DO_ANO_ZERO_VENTO= 5.099
var POTENCIA_DO_ANO_ZERO_BIOMASSA = 0.653

var CUSTO_TOTAL_DO_ANO_ZERO = 0.00 #valor 2014???? #i.e. custo da potência de todas as fontes renováveis consideradas
var CUSTO_DO_ANO_ZERO_SOLAR = 0.00
var CUSTO_DO_ANO_ZERO_VENTO = 0.00
var CUSTO_DO_ANO_ZERO_BIOMASSA = 0.00

var PIB_DO_ANO_ZERO = 169110000000

var CAPITAL_DO_ANO_ZERO = 532630000000

var EFF1960 = 0.12 #Eficiência Agregada de 1960 (12%)
var EFICIENCIA_AGREGADA_DO_ANO_ZERO = 0.1638 #16.38% #valor a ser corrigido

var SHARES_EXERGIA_FINAL_TRANSPORTES_DO_ANO_ZERO = 0.3497 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_DO_ANO_ZERO = 0.3748 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_DO_ANO_ZERO = 0.1608 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_DO_ANO_ZERO = 0.1147 #percentagem decimal

var SHARES_EXERGIA_FINAL_TRANSPORTES_CARVAO_DO_ANO_ZERO = 0.00 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_CARVAO_DO_ANO_ZERO = 1.00 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_CARVAO_DO_ANO_ZERO = 0.00 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_CARVAO_DO_ANO_ZERO = 0.00 #percentagem decimal

var SHARES_EXERGIA_FINAL_TRANSPORTES_PETROLEO_DO_ANO_ZERO = 0.69193929 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_PETROLEO_DO_ANO_ZERO = 0.2247621 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_PETROLEO_DO_ANO_ZERO = 0.06297832 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_PETROLEO_DO_ANO_ZERO =  0.02032029 #percentagem decimal

var SHARES_EXERGIA_FINAL_TRANSPORTES_ELETRICIDADE_DO_ANO_ZERO = 0.00633745 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_ELETRICIDADE_DO_ANO_ZERO = 0.3920005 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_ELETRICIDADE_DO_ANO_ZERO = 0.25003673 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_ELETRICIDADE_DO_ANO_ZERO =  0.35162532 #percentagem decimal

var SHARES_EXERGIA_FINAL_TRANSPORTES_GAS_NATURAL_DO_ANO_ZERO = 0.00717314 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_GAS_NATURAL_DO_ANO_ZERO = 0.71186682 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_GAS_NATURAL_DO_ANO_ZERO = 0.15300413 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_GAS_NATURAL_DO_ANO_ZERO = 0.12795591 #percentagem decimal

var SHARES_EXERGIA_FINAL_TRANSPORTES_COMB_RENOVAVEIS_DO_ANO_ZERO = 0.12144785 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_COMB_RENOVAVEIS_DO_ANO_ZERO = 0.50117928 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_COMB_RENOVAVEIS_DO_ANO_ZERO = 0.35719767 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_COMB_RENOVAVEIS_DO_ANO_ZERO = 0.0201752 #percentagem decimal

var SHARES_EXERGIA_FINAL_TRANSPORTES_HEAT_DO_ANO_ZERO = 0.00 #percentagem decimal
var SHARES_EXERGIA_FINAL_INDUSTRIA_HEAT_DO_ANO_ZERO = 0.91065034 #percentagem decimal
var SHARES_EXERGIA_FINAL_RESIDENCIAL_HEAT_DO_ANO_ZERO = 0.03657347 #percentagem decimal
var SHARES_EXERGIA_FINAL_SERVICOS_HEAT_DO_ANO_ZERO = 0.05277619 #percentagem decimal